Openjdk importer branch
aboutcode-org/vulnerablecode pull request #1589
Opened 2024-09-12 08:50 UTC by harmonicfunc

for issue: #1496 
Added a OpenJDK advisory importer that scrapes the vulnerability data from the link: https://openjdk.org/groups/vulnerability/advisories/ and then added the importer to importer registery

2024-09-12 08:52 UTC, harmonicfunc commented
@TG1999 @ambuj-1211 @ziadhany  please review this pr

2024-09-12 09:18 UTC, keshav-space requested changes
Thanks @harmonicfunc, use the `VulnerableCodeBaseImporterPipeline` for new importers. See the detailed instructions below.

2024-09-12 09:45 UTC, pombredanne commented on vulnerabilities/importers/openjdk.py
> +class OpenJDKImporter(Importer):
@keshav-space this would be a nice addition/update to the doc ;)

2024-09-12 10:29 UTC, harmonicfunc commented
ok, on it

2024-09-12 11:32 UTC, keshav-space commented on vulnerabilities/importers/openjdk.py
> +class OpenJDKImporter(Importer):
@pombredanne ack, will update the doc here https://vulnerablecode.readthedocs.io/en/latest/contributing.html#writing-an-importer

2024-10-19 14:26 UTC, harmonicfunc commented
@keshav-space sorry but do i need to revamp or change logic parts of my code too??

2024-10-29 16:39 UTC, closed without merging

2024-10-30 09:06 UTC, pombredanne commented
@harmonicfunc the core logic does not need change, just the integration in a pipeline!
I see you may have some issues with merging ... this is easy at first! You likely want to rebase or restart on the latest main branch and push a new PR, which I would guess is why you closed this?