Add support for storing  exploitability and weighted severity
aboutcode-org/vulnerablecode pull request #1646
Opened 2024-11-09 00:33 UTC by ziadhany

http://127.0.0.1:8001/api/vulnerabilities :
![Screenshot from 2024-11-09 01-57-51](https://github.com/user-attachments/assets/fa6a8636-cb6e-46d8-a576-5d93d857c3ec)
http://127.0.0.1:8001/vulnerabilities/VCID-dzgg-pppr-zqew :
![Screenshot from 2024-11-09 01-56-23](https://github.com/user-attachments/assets/9469e2da-1a1b-4d75-b8ea-4def5954c998)

2024-11-11 11:53 UTC, tdruez requested changes
See the various comments.
Also, do we have unit tests for all the new code?

2024-11-11 11:53 UTC, tdruez commented on vulnerabilities/migrations/0077_vulnerability_exploitability_and_more.py
> +                max_digits=4,
We want to avoid \n and extra spaces in the help_text.
You should not use the triple quote syntax:
```
help_text="""Exploitability refers to the potential or probability of a software package vulnerability being 
        exploited by malicious actors to compromise systems, applications, or networks. 
        It is determined automatically by the discovery of exploits.""",
```

But instead:
```
help_text=(
    "Exploitability refers to the potential or probability of a software package vulnerability being "
    "exploited by malicious actors to compromise systems, applications, or networks. "
    "It is determined automatically by the discovery of exploits."
),
```

2024-11-11 11:53 UTC, tdruez commented on vulnerabilities/migrations/0077_vulnerability_exploitability_and_more.py
> +                max_digits=4,
"Weighted severity is the highest value calculated by multiplying each severity by its corresponding weight, divided by 10."

2024-11-11 11:53 UTC, tdruez commented on vulnerabilities/models.py
> +        return None
Is there proper unit tests for this one?

2024-11-11 11:53 UTC, tdruez commented on vulnerabilities/models.py
> +            return f"{min(float(self.exploitability) * float(self.weighted_severity), 10.0):.2f}"
It would be more readable to keep the computation separated from the formatting syntax.

2024-11-11 11:53 UTC, tdruez commented on vulnerabilities/models.py
> +        return None
Not needed.

2024-11-11 11:53 UTC, tdruez commented on vulnerabilities/pipelines/compute_package_risk.py
> +        return (cls.add_vulnerability_risk_score, cls.add_package_risk_score)
`add` is not the best verb to use here.

2024-11-13 14:39 UTC, TG1999 commented
@ziadhany please attach the issues that will be fixed by this PR. Additionally please do not merge this until these 2 https://github.com/aboutcode-org/vulnerablecode/pull/1649 https://github.com/aboutcode-org/vulnerablecode/pull/1636 are merged.

2024-11-14 07:00 UTC, tdruez requested changes
Hi @ziadhany we are nearly there. See the few minor comments.

Also, could you provide some input on https://github.com/aboutcode-org/dejacode/pull/194#issuecomment-2470654962 

> In the design documents, the decimal values are always presented with 1 decimal place: 9.0 - 10.0 but the implementation was made with 2 on the VCIO side. I don't know if that was decided on purpose, but I'm not sure that the second decimal place is adding any values. It makes the UI more dense and does not fit the filter choices. Let's clarify this.

What's your take on this? Was it a particular reason to go with 2 decimal places? I just want to make sure that we are consistent across the apps.

2024-11-14 10:58 UTC, TG1999 commented
@ziadhany https://github.com/aboutcode-org/vulnerablecode/pull/1649 https://github.com/aboutcode-org/vulnerablecode/pull/1636 are merged now, please mention the issue in ticket description.

2024-11-17 04:44 UTC, tdruez approved these changes

2024-11-17 04:44 UTC, tdruez commented on vulnerabilities/models.py
> +    )
You reverted back to the """ formatting.

2024-11-18 12:31 UTC, TG1999 commented on vulnerabilities/pipelines/compute_package_risk.py
> -            Package.objects.filter(affected_by_vulnerabilities__isnull=False).prefetch_related(
Seems to me Keshav changes are removed

2024-11-18 12:31 UTC, TG1999 requested changes
See my comment!

2024-11-18 14:30 UTC, ziadhany commented on vulnerabilities/pipelines/compute_package_risk.py
> -            Package.objects.filter(affected_by_vulnerabilities__isnull=False).prefetch_related(
@TG1999, I've updated the code, but Keshav left some comments. I'll update it now

2024-11-18 17:12 UTC, ziadhany commented
@keshav-space Thank you for the review, Please let me know if I overlooked anything, and I hope we can move forward with the merge.

2024-11-18 19:28 UTC, ziadhany commented on vulnerabilities/risk.py
> +        if risk := vulnerability.vulnerability.risk_score:
Yes, you're right; I just renamed it.

2024-11-18 20:45 UTC, keshav-space approved these changes
Thanks @ziadhany, Looking Good!

2024-11-19 04:11 UTC, TG1999 approved these changes
LGTM!

2024-11-19 04:11 UTC, merged